// Generated by ts-to-zod
import { z } from 'zod';

export const fundraiserSchema = z.object({
  data: z.object({
    attributes: z.object({
      title: z.string(),
      shortDescription: z.string(),
      goal: z.number(),
      story: z.string(),
      donationLink: z.string(),
      slug: z.string(),
    }),
  }),
});

export const pageSchema = z.object({
  data: z.object({
    attributes: z.object({
      title: z.string(),
      slug: z.string(),
      content: z.string(),
    }),
  }),
});

export const internalLinkSchema = z.object({
  id: z.number(),
  title: z.string(),
  page: pageSchema,
});

const navigationLinkSchema = z.object({
  __component: z.literal('link.navigation-link'),
  id: z.number(),
  title: z.string(),
  page: pageSchema,
});

const navigationDropDownSchema = z.object({
  title: z.string(),
  __component: z.literal('link.nav-drop-down'),
  links: z.array(internalLinkSchema),
});

export const navigationItemsSchema = navigationLinkSchema.or(
  navigationDropDownSchema
);

export const navigationMenuSchema = z.object({
  data: z.object({
    attributes: z.object({
      includeHomePage: z.boolean(),
      includeFAQ: z.boolean(),
      includeContactForm: z.boolean(),
      pages: z.array(navigationItemsSchema),
    }),
  }),
});

export const footerSchema = z.object({
  footerResourceLinks: z.array(internalLinkSchema),
});

export const fieldComponentSchema = z.union([
  z.literal('form-fields.text'),
  z.literal('form-fields.drop-down'),
]);

export const fieldTypeSchema = z.union([
  z.literal('short'),
  z.literal('long'),
  z.literal('phone'),
  z.literal('email'),
]);

export const contactFieldSchema = z.object({
  __component: fieldComponentSchema,
  name: z.string(),
  isRequired: z.boolean(),
  type: fieldTypeSchema,
  note: z.string(),
  allowOther: z.boolean(),
  entries: z.tuple([
    z.object({
      value: z.string(),
    }),
  ]),
});

export const strapiImageSchema = z.object({
  name: z.string(),
  alternativeText: z.string(),
  caption: z.string(),
  url: z.string(),
});

export const socialSchema = z.object({
  url: z.string(),
  logoAltText: z.string(),
  SocialMediaLogo: z.object({
    data: z.object({
      attributes: strapiImageSchema,
    }),
  }),
});

export const featuredFundraiserSchema = z.object({
  title: z.string(),
  shortDescription: z.string(),
  icon: z.object({
    data: z.object({
      attributes: strapiImageSchema,
    }),
  }),
  fundraiser: z.object({
    data: z.object({
      attributes: fundraiserSchema,
    }),
  }),
});

export const homePageSchema = z.object({
  data: z.object({
    attributes: z.object({
      featured: featuredFundraiserSchema,
      resourceLinks: z.array(internalLinkSchema),
    }),
  }),
});
